/**
 * One-time data-bake: parse the fetched Ensembl TP53 region (GFF3 + FASTA) with
 * GeneO's own parsers and emit src/renderer/src/data/genome.ts as a static
 * assembly (real GENCODE gene models + GC signal + GC-rich regions).
 *
 * Run: npx vite-node scripts/build-genome.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import { parseGff } from '@/genome/gff'
import { computeGcSignal } from '@/genome/signal'
import { gcContent } from '@core/sequence'
import type { Chromosome, GenomeAssembly, GenomeFeature, Track } from '@/genome/types'

const CHR17_LEN = 83257441 // GRCh38 chr17
const WIN_START0 = 7660000 - 1

const gffText = readFileSync('scripts/fixtures/tp53.gff3', 'utf-8')
const faText = readFileSync('scripts/fixtures/tp53.fa', 'utf-8')
const bases = faText.slice(faText.indexOf('\n') + 1).replace(/[^A-Za-z]/g, '').toUpperCase()

const chrom: Chromosome = {
  name: 'chr17',
  length: CHR17_LEN,
  seq: { start: WIN_START0, bases }
}

const transcripts = parseGff(gffText)
  .filter((t) => t.chrom === 'chr17')
  .sort((a, b) => a.start - b.start)

const genesTrack: Track = {
  id: 'trk_gencode',
  name: 'GENCODE genes',
  kind: 'genes',
  visible: true,
  transcripts
}

const gcTrack: Track = {
  id: 'trk_gc',
  name: 'GC Percent',
  kind: 'signal',
  visible: true,
  color: '#5fb88f',
  signal: computeGcSignal(chrom, 200)
}

// GC-rich regions: 200 bp windows with GC >= 55%, merged when adjacent.
const win = 200
const rich: GenomeFeature[] = []
let runStart = -1
for (let i = 0; i < bases.length; i += win) {
  const gc = gcContent(bases.slice(i, i + win))
  const pos = WIN_START0 + i
  if (gc >= 0.55) {
    if (runStart < 0) runStart = pos
  } else if (runStart >= 0) {
    rich.push({ id: `gcrich_${runStart}`, name: 'GC-rich', chrom: 'chr17', start: runStart, end: pos, strand: 0, type: 'region', color: '#c0a040' })
    runStart = -1
  }
}
if (runStart >= 0) rich.push({ id: `gcrich_${runStart}`, name: 'GC-rich', chrom: 'chr17', start: runStart, end: WIN_START0 + bases.length, strand: 0, type: 'region', color: '#c0a040' })

const richTrack: Track = {
  id: 'trk_gcrich',
  name: 'GC-rich regions',
  kind: 'features',
  visible: true,
  features: rich
}

const assembly: GenomeAssembly = {
  id: 'grch38_tp53',
  name: 'Human GRCh38 — TP53 locus',
  chromosomes: [chrom],
  tracks: [genesTrack, richTrack, gcTrack],
  defaultLocus: { chrom: 'chr17', start: 7661000, end: 7688500 }
}

const header = `/**
 * Bundled sample genome assembly — the real human TP53 locus (Ensembl GRCh38
 * chr17:7,660,000-7,700,000): GENCODE gene models, a GC-percent signal track,
 * and computed GC-rich regions. GENERATED by scripts/build-genome.ts — do not
 * edit by hand.
 */
import type { GenomeAssembly } from '../genome/types'

export const sampleGenome: GenomeAssembly = `

writeFileSync(
  'src/renderer/src/data/genome.ts',
  header + JSON.stringify(assembly) + '\n'
)

console.log(`Wrote data/genome.ts: ${transcripts.length} transcripts, ${rich.length} GC-rich regions, ${gcTrack.signal!.spans.length} GC bins, ${bases.length} bp sequence.`)
